string DLG_TEXT[44] = {
"Welcome to the house of ",
". Have you come on business?",
"No, just paying a social call.",
"Yes, I was wondering if you have any work for a captain with a ship?",
"Ask my ",
", who handles that side of our affairs.",
"Thank you, I shall do that.",
"I'm here to ask about ",
"Yes, #spronoun# recently married my ",
"But not willingly. ",
" was brought here by an armed gang.",
"Do you have evidence to back up this ridiculous claim?",
"Yes, a citizen of #sIsla Muelle# told me about the abduction. And I have spoken to someone who received a report of ",
" being brought here.",
"Rumours and hearsay, then. If you repeat this nonsense again, especially outside these walls, I shall have you charged with slander.",
"Then I shall have to get better evidence. And when I do, it won't be legal action which I shall take!",
"You are not welcome here. Leave now before I haved you thrown out!",
"That would be a good trick if you could do it. However, I'm leaving anyway.",
"Where did you come from? You did not enter through the front door, I would have seen you.",
"From that door to the side.",
"Impossible! The corridor on the other side is half collapsed and anyway the lock has been jammed shut for ages.\nI am planning to get some workmen in to clear the passage. It leads to the old Inquisition prison, you know.\nI'll have it cleaned up and open it as a museum, then charge people money to visit it.",
"I've got news for you. ",
" got there first. The cells are perfectly usable, and right now ",
" is in one of them.",
"Nonsense! ",
" is married to ",
"Nevertheless, #spronoun# is in a cell down there. And there must be a key here somewhere. So either you give it to me or I turn this house upside down until I find it.",
"I tell you, there is no key! Wait, though... you look like the sort of person who could use this. We took it from the last person who tried to burgle this house. Will that satisfy you?",
"Yes, I ought to be able to open the cell with that.",
"What the blazes!",
"Allow me to introduce ",
", recently a 'guest' of your #skid#.",
"I shall not tell you. You probably intend to harm ",
". And now you will probably threaten me, so know this. I am old and my life is almost over, but ",
" is in #spronoun# prime. If my death will save #spronoun2# then so be it. So if you are going to kill or torture me, get on with it.",
"No, I shall not do that. Your punishment will be to learn in due time that ",
" is not as honourable as you, and is unworthy of such devotion. Goodbye.",
"Yes, I hired ",
" as an officer and #spronoun# was kidnapped while on shore leave. And I have spoken to someone who received a report of ",
"Yes, I heard that there was a lot of wine left over after the party for ",
" and your #skid#. Perhaps I could buy it from you and take it somewhere where it will be appreciated?",
"Why would we do that? ",
" has #spronoun# own ship and has already taken the wine to sell elsewhere.",
"Oh well, it was worth a try. Thank you for your time anyway.",
}