string DLG_TEXT[22] = {
".",
".",
"You're a friend of that nice young #sperson# who moved here a few weeks ago, aren't you?",
"Yes. Why do you ask?",
"I have terrible news for you. #spronoun# has been kidnapped! #spronoun# was walking around and a gang of men grabbed #spronoun2# and made off. As you'd expect, the soldiers did nothing - makes you wonder why anyone pays taxes!",
"Any idea where they took #spronoun2#?",
"No, there's only one way out of this area and I couldn't see where they went next.",
"I see. Well, thanks for letting me know anyway. Goodbye.",
"Ah, another visitor to the #smerchant# house. Do you know its history?",
"No, is it interesting?",
"They say when Spain owned #sisland_Redmond#, that house belonged to the Inquisition. Not surprising, with its view over the wall.",
"Good way to spy on the governor, then. What else did they get up to?",
"Well, the story is that the Inquisition had their prison somewhere down that dungeon next door. Tortured people, they did. And to this day the dungeon is haunted by the ghosts of their victims.",
"Ghosts? There are no such things as ghosts!",
"That's probably what the gang who took that young #sperson# down there thought. But nobody who goes down there comes out again. Don't say I didn't warn you!",
"True enough. If I do go down there and run into your ghosts, I won't be able to say anything much. Thanks for the warning, though!",
"Welcome, capitan! What do you want?",
"I'm looking for one of my officers. Has a #sperson#, young and probably looking like a noble, been here recently?",
"Yes. A group of sailors were also in here for #spronoun#. At first #spronoun2# seemed willing to go with them, then there was an argument but #spronoun2# went with them anyway. One of them may have had a hidden gun.",
"They can't have been my crew. If they'd brought my officer back to my ship, I'd have known about it. Thanks anyway.",
"Perhaps not. But the story also goes that the Inquisition hid all the gold they took from their victims down there. So occasionally someone goes looking for it. And they never come back out.",
"Gold? Whatever is down there isn't ghosts, but if there's gold, it's going to be mine. Thanks for the warning about the 'ghosts', though!",
}